name: cfn-policy-validator-workflow

on:
  pull_request:
    types: [opened, review_requested]
  push:
    branches:
       - 'main'

permissions:
  id-token: write
  contents: read
  issues: write

jobs: 
  cfn-iam-policy-validation: 
    name: iam-policy-validation
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        id: checkOut
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: configureCreds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
          aws-region: us-east-1
          role-session-name: GitHubSessionName
        
      - name: Install cfn-policy-validator
        id: installCfnVal
        run: pip install cfn-policy-validator

      - name: Validate templates
        id: validateTemplates
        run: |
          set +e
          result=$(cfn-policy-validator validate --template-path ./*.yaml --region us-east-1)
          blocking=$(echo $result | jq '.BlockingFindings[]')
          if [ "$blocking" ]; then 
              for row in $(echo "${blocking}" | jq -r '.[]'); do
              _jq() {
              echo ${row} | jq -r ${1}
              }
            echo "message=$(_jq '.message')" >> $GITHUB_OUTPUT
          done;fi
        shell: bash

      - name: Fetch critical actions from s3
        id: getCriticalActions
        run: |
          echo "actionsLst=$(aws s3 cp ${{ secrets.CRITICAL_ACTIONS }} -)"  >> $GITHUB_OUTPUT
        shell: bash
  
      - name: check-access-not-granted
        id: checkAccessNotGranted
        run: |
          set +e
          result=$(cfn-policy-validator check-access-not-granted --template-path ./*.yaml --actions ${{ steps.getCriticalActions.outputs.actionsLst }} --region us-east-1)
          blocking=$(echo $result | jq '.BlockingFindings[]')
          if [ "$blocking" ]; then echo "result=$blocking" >> $GITHUB_OUTPUT;fi
        shell: bash

      - name: post-results-to-comment
        if: success() || failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.validateTemplates.outputs.result }} \n ${{ steps.checkAccessNotGranted.outputs.result }} '
            }) 

  cfn-template-deploy:
    if: github.branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: MyStack
          template: sample-role.yaml